### PR TITLE
Add Symfony 6 support

### PR DESCRIPTION
**Pull request by qstiegler**
Please extend the requirements to Symfony 6

### CODE REVIEW

**Comment by DylanGD** [comment]
+1 Please provide Symfony 6 support

**Review by DylanGD — APPROVED** [review]

**Comment by theofidry** [comment]
Did you test if it works as is with Symfony6?

**Comment by qstiegler** [comment]
Yes I did, we're already using it by my fork.

**Comment by theofidry** [comment]
Thank you @qstiegler.

I'm not too happy to simply merge this as there is a lot of things wrong here: missing tests & non-existent CI. But that's on use and I'll rather try to fix that for a latter version.

So meanwhile if that seems to do the trick let's go with it.

**Comment by theofidry** [comment]
Ha looks like it's master but should be on 1.x instead. Or were you using master?

**Comment by qstiegler** [comment]
I might have used master...I didn't know that this would be a difference. What do you want me to do now?

**Comment by theofidry** [comment]
It's fine then I guess I should tag an alpha or something

**Comment by qstiegler** [comment]
@theofidry do you know when you'll make a release for that?

**Comment by theofidry** [comment]
I had a look but it's been a while. So I don't think it's wise to do a release on 1.x, there is actually a few BC breaks.

2.0 is not really ready though but since there is a few users on it like you, I've tagged an alpha. This way to you can have a tag but it does not force us to think of a 3.x version yet (I do have quite a few changes still planned for 2.x).

**Pull request merged**
